### ISSUE TITLE
The Typescript dependency version is too broad

### ISSUE THREAD

**Issue by igr** [SchweizerischeBundesbahnen/esta-webjs-2#68]
Currently, the version set in the `package.js` is:

```
"typescript": "^2.3.4",
```

Angular CLI 4.4.3 requires:

```
@angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0' but 2.6.2 was found instead.
```

If user has typescript version e.g. `2.6.2` the project will not work. The workaround is to install required version manually:

```
npm install typescript@'>=2.1.0 <2.4.0'
```

The fix should be specifying the typescript to `2.3.4` in `package.js`.

**Comment by ReToCode** [comment]
We updated to angular 5.1.0 and the corresponding angular cli. Should be fixed on the current state of "master". Btw, thanks for using our stack :) Do you have a similar enterprise setup?
